name: LaTeX to PDF Generation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual triggering

jobs:
  generate:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install MiKTeX
        run: |
          choco install miktex -y
        shell: pwsh

      - name: Setup MiKTeX Path
        run: |
          echo "C:\Program Files\MiKTeX\miktex\bin\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Install LaTeX Packages
        run: |
          miktex --verbose packages update
          
          # Basic packages
          miktex --verbose packages install babel-german
          miktex --verbose packages install fontenc
          miktex --verbose packages install xcolor
          miktex --verbose packages install geometry
          
          # TikZ and related packages
          miktex --verbose packages install pgf
          miktex --verbose packages install tikz-qtree
          
          # Math and formatting packages
          miktex --verbose packages install amsmath
          miktex --verbose packages install array
          miktex --verbose packages install calc
          miktex --verbose packages install enumerate
          miktex --verbose packages install seqsplit
          miktex --verbose packages install multicol
          miktex --verbose packages install siunitx
          
          # Additional required packages
          miktex --verbose packages install latex-tools
          miktex --verbose packages install latex-bin
          miktex --verbose packages install latex-fonts
        shell: pwsh

      - name: Run Generation Script
        run: |
          cd src/demos/latex-demo/scripts
          ./generate-latex.bat
        shell: cmd

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: mock-exam-${{ github.run_number }}
          release_name: Mock Exam ${{ github.run_number }}
          body: |
            Automatically generated mock exam and solutions
            Generated on ${{ github.event.repository.updated_at }}
          draft: false
          prerelease: false

      - name: Upload Exam PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/demos/latex-demo/output/Probeklausur.pdf
          asset_name: mock-exam.pdf
          asset_content_type: application/pdf

      - name: Upload Solutions PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/demos/latex-demo/output/ProbeklausurLosung.pdf
          asset_name: mock-exam-solutions.pdf
          asset_content_type: application/pdf
